# An example for better_launch's declarative launchfiles.
# By the way, the first comment block becomes the launchfile's help text :)

# Any keys that are not part of a table are considered launch arguments. 
# This launch arg is a bool with no default.
enable = bool

# Comments above any block become help text when run with --help.
pkg = "better_launch"

# This block will call BetterLaunch.find with the provided arguments. The result will 
# be stored in a variable called "a_simple_cube" and can be used later in substituions.
# Skipped call tables will store a None result.
[a_simple_cube]
# Only run if pkg was defined (based on python truthiness). You can also use "unless".
if = "${enable}"
func = "find"
package = "${pkg}"
filename = "cube.sdf"

# Blocks are executed in sequence, so we can now use the result of the previous one.
[print_me_baby]
func = "log"
severity = "info"
message = "SUCCESS! A simple cube can be found at ${a_simple_cube}"
