name: Draft PDF
on:
  push:
    paths:
      - docs/paper.*
      - .github/workflows/joss.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: docs/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # Note: this should be the same directory as the input paper.md
          path: docs/paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: 'docs/paper.pdf'
