name: Run Unit Test via Pytest

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          path: workspace

      - name: Build ROS2 workspace
        uses: ichiro-its/ros2-ws-action@v1.0.0
        with:
          distro: jazzy

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run pytest
        run: |
          pytest tests/test_launcher.py --doctest-modules 
